version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/deployments/online"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/deployments/demo-vm"
    schedule:
      interval: "weekly"
